name: Deploy KeepActive Pro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Static Site (index.html)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          allow_empty_commit: true

  build-windows:
    name: Package KeepAwake Script (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload Windows Script
        uses: actions/upload-artifact@v4
        with:
          name: KeepAwake-Windows
          path: windows/KeepAwake.vbs
