name: Deploy KeepActivePro (Backend & Frontend)

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy-backend:
    name: Deploy Backend (AWS Lambda)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install Dependencies in Lambda-Compatible Environment
        run: |
          python3 -m pip install --upgrade pip
          pip install --platform manylinux2014_x86_64 --implementation cp --python-version 3.10 --only-binary=:all: -t backend/package/ pydantic
          pip install --no-cache-dir -r backend/requirements.txt -t backend/package/

      - name: Copy Backend Files
        run: |
          cp -r backend/*.py backend/package/

      - name: Create Deployment Package
        run: |
          cd backend/package
          zip -r ../../fastapi_lambda.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name KeepActiveProBackend --zip-file fileb://fastapi_lambda.zip

  deploy-frontend:
    name: Deploy Frontend (S3 + CloudFront)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Sync Frontend Files to S3
        run: |
          aws s3 sync frontend/ s3://keepactivepro-eu-north-1/ --delete

      - name: Invalidate CloudFront Cache (Ensure New Content Loads)
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
