name: Build and Deploy KeepActivePro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    name: Validate Scripts & Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Skip Linux and macOS validation for now
      - name: Verify Windows VBScript
        run: test -f windows/KeepAwake.vbs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_files: |
            .github/**
            windows/**
            .gitignore
            LICENSE
            README.md

  release:
    name: Create Release with Scripts
    needs: validate-and-deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }} - Windows
          draft: false
          prerelease: false

      - name: Upload Windows Script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows/KeepAwake.vbs
          asset_name: KeepAwake.vbs
          asset_content_type: application/x-vbscript