name: Deploy to AWS

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./assets s3://keepactivepro.com/assets/ --delete --region eu-north-1
          aws s3 cp ./index.html s3://keepactivepro.com/ --region eu-north-1
          aws s3 cp --recursive ./templates s3://keepactivepro.com/templates/ --region eu-north-1
          
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3BFFFFCSYQV57 --paths "/*"

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  

      - name: Install Dependencies and Package Lambda Function
        run: |
          mkdir -p backend/package
          pip install --no-cache-dir --upgrade -r requirements.txt -t backend/package/
          cp -r templates backend/package/templates
          cd backend/package
          zip -r lambda_function.zip .

      
      - name: Verify Zip File Exists
        run: |
          if [ ! -f "backend/package/lambda_function.zip" ]; then
            echo "Error: lambda_function.zip not found!"
            exit 1
          fi

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name keepactivepro-api --zip-file fileb://backend/package/lambda_function.zip --region eu-north-1
