  deploy-backend:
    name: Deploy Backend (AWS Lambda)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install Dependencies and Package FastAPI for Lambda
        run: |
          # Create a deployment package directory
          mkdir -p backend/package

          # Install dependencies inside package/
          pip install --no-cache-dir --upgrade -r backend/requirements.txt -t backend/package/

          # Verify `pydantic` and `pydantic_core` are installed
          ls -l backend/package/pydantic* || true

          # Copy all backend files
          cp -r backend/*.py backend/package/
          cp -r backend/models.py backend/package/
          cp -r backend/database.py backend/package/
          cp -r backend/metrics_handler.py backend/package/
          cp -r frontend backend/package/frontend  # If frontend files are needed

          # Navigate to package directory and zip everything
          cd backend/package
          zip -r fastapi_lambda.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name KeepActiveProBackend --zip-file fileb://backend/package/fastapi_lambda.zip
