deploy-backend:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Build Lambda Package
      run: |
        docker run --rm -v $(pwd):/app -w /app public.ecr.aws/lambda/python:3.8 /bin/bash -c "
          mkdir -p backend/package
          pip install --no-cache-dir --upgrade -r backend/requirements.txt -t backend/package/
          mkdir -p backend/package/backend
          cp backend/*.py backend/package/backend/
          mv backend/package/backend/main.py backend/package/backend/lambda_function.py
          cd backend/package
          zip -r ../fastapi_lambda.zip .
        "

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name KeepActiveProBackend --zip-file fileb://backend/fastapi_lambda.zip

    - name: Update Lambda Handler
      run: |
        aws lambda update-function-configuration --function-name KeepActiveProBackend --handler backend.lambda_function.lambda_handler